rvm: '2.2.3'
script: bundle exec rspec spec
script:
  - bundle exec bin/rake db:create
  - bundle exec bin/rake db:migrate
  - bundle exec rspec spec
  - node_modules/karma/bin/karma start my.conf.js --single-run
language: node_js
node_js:
  - 6.2
before_script:
  - npm install
  - npm install -g bower
  - npm install -g gulp
  - npm install phantomjs
  - npm install -g karma
  - bower install
  - gulp build
  - gulp style
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
