rvm: '2.2.3'
script: bundle exec rspec spec
script:
  - bundle exec bin/rake db:create
  - bundle exec bin/rake db:migrate
  - bundle exec rspec spec
language: node_js
node_js:
  - 0.8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
